### ISSUE TITLE
ConDor Error

### ISSUE THREAD

**Issue by oscarwallnoefer** [mariemorel/condor#9]
Hi,
I have a question regarding the use of ConDor. I'm trying to use the software from the website. However, after a few minutes, the process stops, leaving this output:

Job Status:
        ID: 33d561ba-2c35-4255-525b-02f32153a17b
        Name: prova_UQCRFS1
        Status: Error
        Submited on: Mar 14, 2024 11:46:25 UTC
        Started on: Mar 14, 2024 11:46:56 UTC
        Ended on: Mar 14, 2024 11:56:09 UTC
        Total time elapsed: 9m44s
        Output message: Galaxy Error
    Job configuration:
        Run mode: condor
        Min #eems: 2
        Min #convergence sequences: 10
        Pvalue emergence: 0.1
        log BF Correlation: 10
        Input sequences: 59
        Alignment Length: 297
        Evolutionary model: best (Frequencies: Fmodel)

I suspect there might be something wrong with the input file set. Could you please help me? I'm attaching the files used below.
[tag.txt](https://github.com/mariemorel/condor/files/14606208/tag.txt)
[outgroup.txt](https://github.com/mariemorel/condor/files/14606213/outgroup.txt)
[UQCRFS1.zip](https://github.com/mariemorel/condor/files/14606228/UQCRFS1.zip)

Thank you, 
Oscar

**Comment by fredericlemoine** [comment]
Dear Oscar,

Thank you for using CONDOR.
I tested your dataset, and it appears that the tree has 2 nodes with the same annotation '{Foreground}', which is considered as a duplicate node name.
If you remove it seems to work.

By the way, you can also use [gotree](https://github.com/evolbioinfo/gotree) to automatically remove internal node names of your tree:
```
gotree rename -e ".*" -b "" --internal --tips=false -i tree.newick
```

Do not hesitate to ask me if you need more infomation,

Frederic

**Comment by oscarwallnoefer** [comment]
Thank you very much for the help and patience, it was a silly mistake.
I would have another question then: how can I test the convergence between two deep nodes? In my dataset, I want to test the convergence between two species (Pogona vitticeps and Phrynocephalus versicolor) and all the snakes (all the remaining species in the tag.txt file). Is it possible to do it with Condor or do I need to look for another program?

**Comment by mariemorel** [comment]
Dear Oscar, 

ConDor doesn't directly measure convergence between species.
It aims to detect convergent mutations based on an alignment and the annotation at the tips of a corresponding tree. 
So the hypothesis would be that your two species and all the snakes are convergent because they would share a phenotype or a common environment and then ConDor would output the mutations that support this convergence and are significant. 

Annotating your two species and all the snakes as convergent (tag file) you would obtain as a result of running ConDor, all the convergent mutations shared by these species. 
I hope this answers your question,

Marie.

**Comment by oscarwallnoefer** [comment]
Dear @mariemorel,

thank you for your assistance, now it is more clear!
Best regards, 

Oscar
